language: csharp
mono: none

dist: xenial

script:
 - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
 - sudo dpkg -i packages-microsoft-prod.deb > /dev/null
 - sudo apt-get install -y -qq apt-transport-https > /dev/null
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq dotnet-sdk-2.2 > /dev/null
 - dotnet restore > /dev/null
 - dotnet build --no-restore
 - dotnet test