language: csharp
mono: none

dist: xenial

script:
 - wget -q https://packages.microsoft.com/config/ubuntu/16.04/packages-microsoft-prod.deb
 - sudo dpkg -i packages-microsoft-prod.deb
 - sudo apt-get install -y -qq apt-transport-https 
 - sudo apt-get update -qq
 - sudo apt-get install -y -qq dotnet-sdk-2.2
 - dotnet restore
 - dotnet build
 - dotnet test